theme: jekyll-theme-leap-day
title: 100 Days of Code Log
description: by [Your Name]
#google_analytics: UA-121627234-4

exclude: [
  Gemfile,
  Gemfile.lock,
  node_modules/,
  gruntfile.js,
  package-lock.json,
  package.json,
  src/
]
# url: http://localhost